[build]
  publish = "."
  functions = "netlify/functions"

# Rediriger les appels API vers les fonctions serverless
[[redirects]]
  from = "/api/data"
  to = "/.netlify/functions/data"
  status = 200

[[redirects]]
  from = "/api/details"
  to = "/.netlify/functions/details"
  status = 200

# La racine pointe vers l'index principal (Catalogue)
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
